# Generated by Django 4.2.13 on 2024-05-15 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycle_store_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type_bicycle', models.TextField(max_length=100)),
                ('vehicle_type_tricycle', models.TextField(max_length=100)),
                ('vehicle_type_unicycle', models.TextField(max_length=100)),
                ('number_in_stock', models.PositiveIntegerField()),
            ],
        ),
    ]
