# Generated by Django 4.2.13 on 2024-05-16 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cycle_store_app', '0002_vehicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_type_bicycle',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_type_tricycle',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_type_unicycle',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='type',
            field=models.CharField(choices=[('unicycle', 'Unicycle'), ('bicycle', 'Bicycle'), ('tricycle', 'Tricycle')], default='bicycle', max_length=100),
        ),
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('paid', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cycle_store_app.customer')),
                ('order', models.ManyToManyField(to='cycle_store_app.vehicle')),
            ],
        ),
    ]
