# Generated by Django 4.2.13 on 2024-05-16 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycle_store_app', '0003_remove_vehicle_vehicle_type_bicycle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='type',
            field=models.CharField(default='bicycle', max_length=100),
        ),
    ]
