# Generated by Django 4.2.13 on 2024-05-17 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cycle_store_app', '0004_alter_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_order', to='cycle_store_app.customer'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='number_in_stock',
            field=models.PositiveIntegerField(verbose_name=1),
        ),
    ]
